require('settings')
require('keymaps')

vim.cmd('colorscheme tokyonight-night')

require('plugins')
require('plugins.configs.telescope')
require('plugins.configs.lualine')
require('plugins.configs.treesitter')
require('plugins.configs.lsp-config')
require('plugins.configs.cmp')
require('plugins.configs.autopairs')
require('plugins.configs.nvimtree')
require('plugins.configs.comment')
require('plugins.configs.toggleterm')
require('plugins.configs.bufferline')
require('plugins.configs.gitsigns')
require('plugins.configs.null-ls')
